CREATE TABLE IF NOT EXISTS ALLOCATION_WINDOW_CONFIG (
    configID INT PRIMARY KEY,
    initialAllocationDate DATETIME NOT NULL,
    finalAllocationDate DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);
