CREATE TABLE IF NOT EXISTS AUTO_ALLOCATION_LOG (
    logID INT PRIMARY KEY AUTO_INCREMENT,
    triggeredByAdminID VARCHAR(20) NULL,
    triggeredAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalAllocationDate DATETIME NULL,
    eligibleCount INT NOT NULL DEFAULT 0,
    matchedCount INT NOT NULL DEFAULT 0,
    unassignedCount INT NOT NULL DEFAULT 0,
    logStatus VARCHAR(30) NOT NULL,
    resultMessage VARCHAR(500) NOT NULL,

    FOREIGN KEY (triggeredByAdminID) REFERENCES USER(userID) ON DELETE SET NULL ON UPDATE CASCADE
);
