CREATE TABLE IF NOT EXISTS ELIGIBILITY_RULE_CONFIGURATION (
    ruleID INT PRIMARY KEY,
    minimumCGPA DECIMAL(3, 2) NOT NULL DEFAULT 2.00,
    requiredNextSemester VARCHAR(10) NOT NULL DEFAULT 'Y2S3',
    blockedAcademicStatus VARCHAR(50) NOT NULL DEFAULT 'EF',
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ELIGIBILITY_RULE_CONFIGURATION
(
    ruleID,
    minimumCGPA,
    requiredNextSemester,
    blockedAcademicStatus
)
VALUES
(
    1,
    2.00,
    'Y2S3',
    'EF'
)
ON DUPLICATE KEY UPDATE
    ruleID = ruleID;
