INSERT IGNORE INTO RESEARCH_TAG (tagName) VALUES
('Artificial Intelligence'),
('Machine Learning'),
('Deep Learning'),
('Data Analytics'),
('Data Science'),
('Cybersecurity'),
('Software Engineering'),
('Web Development'),
('Mobile Application Development'),
('Cloud Computing'),
('Internet of Things'),
('Computer Vision'),
('Natural Language Processing'),
('Database Systems'),
('Human Computer Interaction'),
('Game Development'),
('Blockchain'),
('Network Security'),
('Information Systems'),
('Project Management');
