CREATE TABLE IF NOT EXISTS USER_ACTIVITY_STATUS (
    userID VARCHAR(20) PRIMARY KEY,
    systemRole VARCHAR(50) NOT NULL,
    lastSeenAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isOnline BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (userID) REFERENCES USER(userID) ON DELETE CASCADE ON UPDATE CASCADE
);
